project:
  type: website

website:
  title: "Tabitha Williams"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
        

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

